### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#10]
Phenogrid load and initialize time is slow. Commit https://github.com/monarch-initiative/phenogrid/commit/0084b7f03611e4fa9a02af1ef03e7d998339b3a5 contains firebug profiling calls aimed at elucidating bottlenecks. 

Based on my read of these results, it seems like the creation of gradients, the model labels, and the first part of creating the model rects ("mod-rects-basic") are particularly slow.

note that this is above and beyond delays due to owlsim. My most recent load took about 9.9 seconds, 1.5 of which were on the client side after the data returned. Can we cut this time down?

**Comment by VincentIII** [comment]
Performance Improved
