### ISSUE TITLE
De-highlighting intersection on mouseout doesn't work in IE 11

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#103]
![capture](https://cloud.githubusercontent.com/assets/195873/8781357/7ad56cf6-2edc-11e5-98c6-615ac14141e8.PNG)

**Comment by davism84** [comment]
Should we close this?  It's not an issue with the refactored version, unless we should track this for the current version.  @yuanzhou @harryhoch

**Comment by harryhoch** [comment]
I defer to @yuanzhou
