### ISSUE TITLE
configuration display

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#110]
configuration display, see [#464](https://github.com/monarch-initiative/monarch-app/issues/464)

**Comment by yuanzhou** [comment]
![capture](https://cloud.githubusercontent.com/assets/195873/9495054/8f32dd92-4bd7-11e5-8b9e-d6851c7305f0.PNG)

**Comment by harryhoch** [comment]
let's focus this discussion in https://github.com/monarch-initiative/phenogrid/issues/141
