### ISSUE TITLE
refactor layout

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#111]
(no right/bottom stuff)

**Comment by yuanzhou** [comment]
Noted in PR #153 Moved all the phenogrid controls (Organism, Sort Phenotypes, Calculation Method, and flip axis) into the sliding panel. 

![capture](https://cloud.githubusercontent.com/assets/195873/9227547/2bcaab36-40e2-11e5-9065-9a1dec649833.PNG)

Further fixed display issues in monarch-app, addressed in PR #154 

Will continue to improve the layout design.

**Comment by yuanzhou** [comment]
More changes made in PR #155 

![capture](https://cloud.githubusercontent.com/assets/195873/9341854/52514ae2-45c6-11e5-8063-a3f79c3c43cf.PNG)

**Comment by yuanzhou** [comment]
Tweaked the gradient legend to align all the label texts, and moved monarch logo inside the phenogrid controls, then got rid of the logo on the bottom right, also use the grid region width as the gradient bar width. 

![capture](https://cloud.githubusercontent.com/assets/195873/9451906/67c1ae04-4a7f-11e5-86d1-73523931101a.PNG)

**Comment by yuanzhou** [comment]
Moved the logo outside the control button, further styled the button and popup options. Also moved the FAQ icon next to the top title inside the options panel.

![capture](https://cloud.githubusercontent.com/assets/195873/9470519/62321c9e-4b1a-11e5-8093-26e0e09385e6.PNG)

Below is how it looks after you click that options icon:

![capture1](https://cloud.githubusercontent.com/assets/195873/9470545/71b90420-4b1a-11e5-83c6-600e66afde07.PNG)

**Comment by yuanzhou** [comment]
Moved the rotated species names to the right. PR#159

![capture](https://cloud.githubusercontent.com/assets/195873/9478597/cc3d8fac-4b46-11e5-8dc3-45176e110879.PNG)

**Comment by yuanzhou** [comment]
Can we close this issue? @harryhoch @davism84

**Comment by harryhoch** [comment]
I think so.
