### ISSUE TITLE
expandable panel for show/hiding extra options

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#116]
place sorting, display and flip axis into this expandable panel

**Comment by davism84** [comment]
change flip axis button to check box and maybe label it **Invert Axis**

**Comment by yuanzhou** [comment]
Noted in PR #153 Moved all the phenogrid controls (Organism, Sort Phenotypes, Calculation Method, and flip axis) into the sliding panel. 

![capture](https://cloud.githubusercontent.com/assets/195873/9227547/2bcaab36-40e2-11e5-9065-9a1dec649833.PNG)

Further fixed display issues in monarch-app, addressed in PR #154 

![capture](https://cloud.githubusercontent.com/assets/195873/9250145/c8c95ff2-4198-11e5-9ed0-77ddde548005.PNG)


More changes made in PR #155 

1. grouped elements in overview map, and put it in the upper left corner
2. added logo config and moved logo to bottom right
3. grouped gradient bar and legend texts and moved to bottom, width is calculated based on the gridRegion
4. dynamically position the control panel (button and options)

![capture](https://cloud.githubusercontent.com/assets/195873/9341854/52514ae2-45c6-11e5-8063-a3f79c3c43cf.PNG)

after the control button is clicked:

![capture](https://cloud.githubusercontent.com/assets/195873/9341887/9c95161a-45c6-11e5-9f57-46a9de588735.PNG)

**Comment by harryhoch** [comment]
refer to https://github.com/monarch-initiative/phenogrid/issues/141 for further discussion of configuration
