### ISSUE TITLE
TypeError on anaylze results page

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/phenogrid#119]
I'm getting 

        TypeError: jQuery(...).phenogrid is not a function

 on the analyze results page, for example: http://beta.monarchinitiative.org/analyze/phenotypes/?input_items=MP%3A0001399+HP%3A0006801&mode=search&target_species=all&limit=100

**Comment by harryhoch** [comment]
Ah. monarch-app/Analyze.js must be revised to deal with the new convention for creating a Phenogrid. @yuanzhou, please look into this and make appropriate revisions in Analyze.js, mirroring code that is in 
phenogridloader-no-species.js

**Comment by yuanzhou** [comment]
Already fixed. 

https://github.com/monarch-initiative/monarch-app/commit/84ea9eaea1dc4bd28e43c2f041d15809c009c122
