### ISSUE TITLE
Minify phenogrid-bundle.js

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/phenogrid#120]
phenogrid-bundle.js takes about 1.5-2 seconds to load, would it be possible to minify the file?

**Comment by yuanzhou** [comment]
@kshefchek I'll do a minify before the release. Right now it's good to have that non-minified version for debugging purpose.

**Comment by yuanzhou** [comment]
@harryhoch Do you think I should do the minify for the release version? gulp-uglify is used for this purpose and I add simply add a pile call to do the JS minify. I can also add the css minify.

**Comment by harryhoch** [comment]
sure. if you see no concerns, go for it

On Jul 27, 2015, at 09:08, yuanzhou <notifications@github.com<mailto:notifications@github.com>> wrote:


@harryhoch<https://github.com/harryhoch> Do you think I should do the minify for the release version? gulp-uglify is used for this purpose and I add simply add a pile call to do the JS minify. I can also add the css minify.

-

**Comment by yuanzhou** [comment]
Added js and css minify. 

phenogrid-bundle.js file size 1160K -> 520K
phenogrid-bundle.css file size 51K -> 37K
