### ISSUE TITLE
user-defined labeling for the UI labels

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#123]
Since we are now supporting source, target, and targetgroup internally within the code, we may want to allow the UI labels to be configuration variables so that they can match accordingly
i.e.,  sources = phenotype;
target = gene, disease, model ; 
targetgroup = containers for targets - human, mus musculs, etc.

**Comment by harryhoch** [comment]
@davism84 ,  please work on this as you continue to clean code

**Comment by yuanzhou** [comment]
Added in PR #177
