### ISSUE TITLE
CORS error causes phenogrid to churn with no result

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#125]
On Mac OSX Mavericks and Chrome
* I go to http://beta.monarchinitiative.org/disease/DOID%3A5723 
and click on Compare
* It takes >3 seconds for the "loading phenogrid" message to show up
* Once shown, the spinner doesn't stop

Looking at the source of the problem, I get a 413 (Full head)
The first item in the list is a CORS one: J.ajaxTransport.G.cors.t.crossDomain.send
Please advise; does this have anything to do with having changed the SciGraph URLs in configuration this afternoon?

![screen shot 2015-07-29 at 23 03 19](https://cloud.githubusercontent.com/assets/3658863/8976796/e39273e4-3646-11e5-9fd6-c11ccfa0e5c5.png)

For thoroughness, I should also mention that the same page doesn't load at all on stage, (http://stage.monarchinitiative.org/disease/DOID%3A5723 ) I'm guessing that is expected at present, but please confirm.

**Comment by harryhoch** [comment]
Interesting. 413 HTTP code is a "Request Entity" too large. This page has 663 phenotypes. Ouch. Any thoughts on what we can do here to handle this sort of request? Is Ringo at all configurable? @cmungall ,@kltm

**Comment by yuanzhou** [comment]
The current version still uses HTTP GET to send out those phenotypes, 663 phenotypes may cause the URL too long. Kent has changed it to POST, but I haven't been able to merge his PR due to some local testing errors.

**Comment by cmungall** [comment]
Well it's really 663 phenotype associations, the same phenotype may be 
there twice if it's associated with different leaf diseases. I assume 
they are being uniqified before sent?

**Comment by harryhoch** [comment]
@cmungall, Phenogrid does no filtering of input phenotypes before sending the response to /simsearch. We could add a filter in phenogrid, or in the /simsearch call - where's the best spot?

**Comment by yuanzhou** [comment]
One feed back from today's meeting about filtering the phenotype input is to check duplicated phenotype IDs.

**Comment by yuanzhou** [comment]
Issue fixed after using the ajax POST. @harryhoch

**Comment by yuanzhou** [comment]
Already added check to remove any duplicated phenotypes before sending them out to simsearch.
