### ISSUE TITLE
Notify users when Phenogrid won't load due to an error

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#126]
In the event that Phenogrid won't load due to error(s), it would be good to see a simple notification to the user so that they know what to expect. Perhaps also include an indication of where to log a ticket would be good as well.
See https://github.com/monarch-initiative/phenogrid/issues/125

**Comment by harryhoch** [comment]
yes. @yuanzhou, can you look into the error in https://github.com/monarch-initiative/phenogrid/issues/125, and see if we can handle it more gracefully?

**Comment by yuanzhou** [comment]
Have added the popup dialog for ajax errors, will refine it later
