### ISSUE TITLE
  Tooltip for phenogrid cells - showing species in phenotype label is confusing

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#134]
see https://github.com/monarch-initiative/monarch-app/issues/311

**Comment by harryhoch** [comment]
see also https://github.com/monarch-initiative/phenogrid/issues/59

**Comment by harryhoch** [comment]
see also https://github.com/monarch-initiative/phenogrid/issues/59

**Comment by yuanzhou** [comment]
I noticed this too, it's also redundant to show the species in tooltip.

**Comment by yuanzhou** [comment]
What's the decision on this? Remove species from hover over tooltip? @harryhoch

**Comment by harryhoch** [comment]
@yuanzhou, this needs discussion. see https://github.com/monarch-initiative/monarch-app/issues/311

**Comment by yuanzhou** [comment]
For now I think we still need it especially after clicking the flip button.

**Comment by davism84** [comment]
changed the cell tooltip with the following content. which may resolve this.  what do you think @harryhoch can we close this??

![image](https://cloud.githubusercontent.com/assets/10049022/9614338/4065ff90-50bf-11e5-8f9a-c047364144e4.png)

**Comment by harryhoch** [comment]
yes
> On 1 Sep 2015, at 3:38 PM, Michael Davis <notifications@github.com> wrote:
> 
> changed the cell tooltip with the following content. which may resolve this. what do you think @harryhoch can we close this??
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by nlwashington** [comment]
I am not sure I understand...  the species is listed under "query", rather than the "target" here; i don't actually know what the query is, but i suspect it is a human disease (meaning the query would be homo sapiens).  and it certainly looks like the target is a mus musculus (mouse) gene.  

I would make sure to put the species with the thing it is representing.  

Additionally, it is strange for the similarity to be listed together with the query.  Why not put it with the in-common?

**Comment by harryhoch** [comment]
@davism84, please revise as per Nicole's comments. thanks

**Comment by davism84** [comment]
see update.  @nlwashington @harryhoch 

![image](https://cloud.githubusercontent.com/assets/10049022/9634135/5569353e-515e-11e5-869f-4e43f32e3518.png)

this was the original mockup for the refactor [https://github.com/monarch-initiative/monarch-app/issues/499](https://github.com/monarch-initiative/monarch-app/issues/499)

**Comment by harryhoch** [comment]
@davism84 - thanks. looks good to me.

**Comment by harryhoch** [comment]
@davism84 , can we close this?

**Comment by nlwashington** [comment]
ok for me to close for now.
