### ISSUE TITLE
improve configuration for phenogrid 

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#141]
see https://github.com/monarch-initiative/monarch-app/issues/464 for a detailed design and discusison

**Comment by yuanzhou** [comment]
Updates:

1. Overview mini map's config has been wrapped in `navigator` object in the config. All its children elements are grouped inside the `g` element.
2. Gradient legend related elements are also grouped.
3. Logo is also configurable width and height, the position x and y are calculated based on the grid region.

**Comment by yuanzhou** [comment]
Cleaned up the config/options variables inside `phenogrid.js`, #182 

Now `config` contains all the over writable variables that can be overwritten by Phenogrid constructor. And `internalOptions` has all other config variables that are supposed to be changed/customized by developers who have good understanding of Phenogrid.
