### ISSUE TITLE
Update Uniqueness result to percentage

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#142]
Currently it uses the IC score in common as the Uniqueness result, will change this to a calculated percentage.

According to the help text in popup:

> Uniqueness reflects how often the phenotype-in-common is annotated to all diseases and genes in the Monarch Initiative knowledgebase. This is simply a reflection of the IC normalized based on the maxIC. IC(PhenotypeInCommon)maxIC(AllPhenotypes)

Should the correct calculation be 

````
IC(PhenotypeInCommon) / maxIC(AllPhenotypes)
````

Am I right? @harryhoch

**Comment by yuanzhou** [comment]
Already changed, @harryhoch please double check and let me know if I can close this issue or you can just close it.

**Comment by harryhoch** [comment]
@yuanzhou, I will spend a bit of time on this and let you know later this morning.
