### ISSUE TITLE
remove ontology labels from phenotype labels 

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#145]
See https://github.com/monarch-initiative/monarch-app/issues/871:..

When you run the PhenoGrid starting from a mouse model, you can "click on icon to expand HPO info". However, the ontology is MPO rather than HPO. A similar comment applies to fish terms on the left.
Maybe we should replace this for now with "click to expand phenotype info"

@yuanzhou , please take a look.

**Comment by yuanzhou** [comment]
According to the inoput from @harryhoch, I'll change the text to “expand classification hierarchy”, which I think is more self-explained than HPO or phenotype info.
