### ISSUE TITLE
Remove "collapse" HPO treeview, leave it expanded once built

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#147]
I realized that there's no need to show the text of "collapse xxx", we should just display the classification hierarchy once it's expanded. Because once the treeview is displayed, it's cached, we benefit nothing from collapsing the treeview in the tooltip. And once it's collapses, if we move back to the same phenotype, we still need to click to expand the cached treeview again. Why not just let the treeview stay there once it's expanded?  

![capture](https://cloud.githubusercontent.com/assets/195873/9042083/4ccc3444-39da-11e5-8788-bd2cb982613c.PNG)

![capture1](https://cloud.githubusercontent.com/assets/195873/9042102/7443c73a-39da-11e5-958e-05e79da5f92a.PNG)

**Comment by yuanzhou** [comment]
FYI @davism84, I've removed the collapse HPO related things from `phenogrid.js` and `tooltiprender.js`.

**Comment by yuanzhou** [comment]
FYI @davism84 I've also changed the clickable icon to clickable text (styled it with underline and red color to make it eye-catchy and look like an link)

![capture](https://cloud.githubusercontent.com/assets/195873/9065644/ea47b254-3aa0-11e5-9569-0dbddb3b1b3e.PNG)

**Comment by harryhoch** [comment]
@yuanzhou , looks good. thanks
