### ISSUE TITLE
The information icon obscures the text "Cross Species Overview"

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#149]
I go to page http://beta.monarchinitiative.org/gene/OMIM:168600 and click the "compare" tab.
The information icon should not overlap the words "Cross species overview" or any other text.
![screen shot 2015-08-05 at 12 35 38](https://cloud.githubusercontent.com/assets/3658863/9095933/f4c15126-3b6e-11e5-927f-8e77714085bb.png)

**Comment by yuanzhou** [comment]
@jmcmurry I just checked this page and the icon is in the right place.

![capture](https://cloud.githubusercontent.com/assets/195873/9111714/9aa52894-3c17-11e5-9167-9e06f19f60b2.PNG)

What browser did you use to get this overlapping issue?

**Comment by jmcmurry** [comment]
I'm on Chrome (Mac OSX) however, looking at it today, I don't see it there.
Odd.
