### ISSUE TITLE
install/configure phenogrid on exomiser

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#17]

**Comment by yuanzhou** [comment]
I think this relates to https://github.com/monarch-initiative/monarch-app/issues/970

**Comment by harryhoch** [comment]
yes. we will need to discuss this - soon, perhaps

**Comment by harryhoch** [comment]
going to call this done enough or now.

**Comment by kshefchek** [comment]
Is it worth documenting this pipeline? @julesjacobsen how would we go about getting JSON out of exomiser?
