### ISSUE TITLE
grid title overlays the monarch log

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#179]
in inverted mode. test with following:    /disease/OMIM:183090

![image](https://cloud.githubusercontent.com/assets/10049022/9963852/58e4d764-5dfb-11e5-82f0-e2950bdd0ca2.png)

**Comment by yuanzhou** [comment]
Fixed this by moving logo down a little bit. Please see https://github.com/monarch-initiative/phenogrid/commit/637ce9bc65f81b299287921156108065db1fa893

![capture](https://cloud.githubusercontent.com/assets/195873/10002345/8f215728-6074-11e5-86a1-4f6483422cdb.PNG)
