### ISSUE TITLE
test from Analyze/Phenotypes 

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#181]
make sure we test from this option.  we usually only test from /disease

**Comment by davism84** [comment]
getting the following error

POST:http://monarchinitiative.org/simsearch/phenotype
http://monarchinitiative.org/simsearch/phenotype Failed to load resource: the server responded with a status of 502 (Proxy Error)
localhost/:1 XMLHttpRequest cannot load http://monarchinitiative.org/simsearch/phenotype. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8082' is therefore not allowed access. The response had HTTP status code 502.
phenogrid-bundle.js:1 exception: 0 
phenogrid-bundle.js:1 We're having some problems. Please check your network connection.

**Comment by yuanzhou** [comment]
Tested on my PC and couldn't replicate this error. I believe it's a monarch server issue.

**Comment by yuanzhou** [comment]
Did more tests, and sometimes it took really long time to load the data from simsearch. Must be server issue.

**Comment by davism84** [comment]
Need to adjust parameters to support single or All species selection from the Analyze.js page.
