### ISSUE TITLE
error on return of missing species compare data

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#184]
if no compare results are returned, in this case for Fish, Phenogrid just shows a display dialog with just 'Title' in it, no error message, etc.  NOTE:  other species compare data was returned successfully, if you review the Network response

see  http://monarchinitiative.org/gene/ZFIN:ZDB-GENE-990415-270

![image](https://cloud.githubusercontent.com/assets/10049022/9968554/18a516e8-5e17-11e5-9a80-8c619aff9667.png)

**Comment by yuanzhou** [comment]
I'm guessing that it's caused by monarch server. We had that issue before. And I went to `http://monarchinitiative.org/gene/ZFIN:ZDB-GENE-990415-270` but didn't see this popup dialog.

Please refer to https://github.com/monarch-initiative/monarch-app/issues/903
