### ISSUE TITLE
tooltip box hovering over cell is displayed extra large

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#185]
this only occurs when I run from the index.html file. through monarch-app it's fine

![image](https://cloud.githubusercontent.com/assets/10049022/9968746/27c7136e-5e18-11e5-958d-dced0bb4b5b9.png)

**Comment by yuanzhou** [comment]
Caused due to the #pg_contianer added in front of each CSS ids and classes, but the stickey tooltip is not inside the #pg_container. Simply removed that #pg_container prefix.
