### ISSUE TITLE
change handling of options menu

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#191]
Currently, the options menu closes after each click of a check box or radio button. This complicates the process of making multiple selections.

Can we modify to have a handler execute after each selection, without closing the menu? The menu would effectively stay open until mouse-exit...

**Comment by yuanzhou** [comment]
@harryhoch We realized that a while ago. The reason why the options menu disappears after each click is because currently we call `_redraw()` after each chick and it rerenders all the display.

I'll work on this.

**Comment by harryhoch** [comment]
Ok. thanks. 
> On 22 Sep 2015, at 9:28 AM, yuanzhou <notifications@github.com> wrote:
> 
> @harryhoch We realized that a while ago. The reason why the options menu disappears after each click is because currently we call _redraw() after each chick and it rerenders all the display.
> 
> I'll work on this.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by yuanzhou** [comment]
Now the options menu stays open and it's positioned relative to the grid region. Merged via PR #193
