### ISSUE TITLE
large gap with phenogrid on Analyze page

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#192]
need a way to dynamically change the pg_container height, instead of fixed min_height, see screenshot

![image](https://cloud.githubusercontent.com/assets/10049022/10025213/23f3c5a2-6129-11e5-9b1f-f8596d041736.png)

**Comment by yuanzhou** [comment]
Have this fixed by setting the SVG width and height based dynamically. 

![capture](https://cloud.githubusercontent.com/assets/195873/10046670/2f8ad004-61d8-11e5-9fe2-3534896d9bff.PNG)
