### ISSUE TITLE
Publish phenogrid to npmjs.org

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#196]
Use GPL-2.0 as the correct license.
Use 1.0.0 as the phenogrid version number
Use postinstall for creating bundle files

**Comment by kltm** [comment]
@harryhoch, GPL 2 is an interesting license choice; would it be okay to ask the rationale versus 3 (or LGPL for that matter) or other licenses, or is that a beer-time question? (I understand license negotiation can be a fraught process.)

**Comment by harryhoch** [comment]
@kltm - short answer - this was  compromise between a licensing office who wanted a license that imposed restrictions that would encourage licensing, but yet was afraid of GPL v3, and the desire to have a "pure" open source license - ie, nothing like "BSD for non-commercial use only" allowed. 

The long answer is a beer question.

**Comment by yuanzhou** [comment]
Finalized via PR #197
