### ISSUE TITLE
Grid cell mouseover conflicts with corsshair

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#199]
When we hover over a grid cell, the cell will be highlighted in red and cross hairs and tooltip show up at the same time. If we continue to move mouse carefully inside the cell, when the mouse cursor is right no either vertical or horizontal cross hair, the tooltip will disappear. The cause of this behavior is the cross hair lines are appended to svg after the cell rect is created. And in svg, the elements layer is defined by the order the element appears in the document. We can't use `z-index` to specify the order of the cell rect and cross hair lines.

![capture](https://cloud.githubusercontent.com/assets/195873/10224447/005e252e-682c-11e5-83a4-77e33acbfddd.PNG)

I've tried to append the cross hair lines inside the <g> element of the grid cells, and move the target cell rect to after the cross hair lines. Didn't work.

**Comment by yuanzhou** [comment]
One possible workaround is to create two cross hair lines for each direction, and make sure there's no overlap of the lines with the grid cell. Around the cell, create crosshair-left, crosshair-right, crosshair-top, and crosshair-bottom.

**Comment by harryhoch** [comment]
Is it possible that you need to look at the mouse exit routines for the cell? It might be tat the tooltip disappears when you go into the cross-hair. Do some coordinate checking before closing the tooltip...

**Comment by yuanzhou** [comment]
Thanks @harryhoch I think I figured this out by creating 4 lines around the cell, this way there's no svg elements overlapped. Then I can simply make the highlighted cell the same color as the line's.

![capture](https://cloud.githubusercontent.com/assets/195873/10231034/7d26c562-684e-11e5-82e3-99c9c245001d.PNG)

**Comment by harryhoch** [comment]
ok. that works.
