### ISSUE TITLE
Always show crosshairs highlighting when tooltip is on

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#205]
Just noticed that the crosshairs highlighting shows up only when we hover over the label/cell. At the same time the tooltip shows up. But the crosshairs highlighting is gone when we move the mouse to the tooltip (starting from the invisible container). 

In the screenshots, the blue dot is the cursor since I couldn't capture them.

![capture](https://cloud.githubusercontent.com/assets/195873/10394595/4159b314-6e66-11e5-987f-7250e1281a89.PNG)

![capture2](https://cloud.githubusercontent.com/assets/195873/10394597/434be0d4-6e66-11e5-9f07-94a43ef53993.PNG)

@harryhoch I think the crosshairs highlighting should always show up even when the mouse is on the gap and tooltip.

**Comment by yuanzhou** [comment]
@harryhoch Do you think it's better to keep the highlighting srosshairs on when move mouse over tooltip?

**Comment by harryhoch** [comment]
well, how hard is it to retain the highlighting on the crosshairs? If its not difficult, let's fix.

**Comment by yuanzhou** [comment]
Not hard. I've got most part of the work done. Basically just to wrap the crosshair on/off functions as well the highlighting on/off functions separately, and reuse them for mouseover/mouseout label/cell and mouseover/mouseout tooltip. This fix will also clean up many code and make future work easier.

**Comment by harryhoch** [comment]
great. thanks

**Comment by yuanzhou** [comment]
Addressed in PR #207
