### ISSUE TITLE
size and scrolling issues & improvements

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/phenogrid#22]
i think the overall dispaly and navigation for the phenogrid needs improvement.  while the mini-map is really neat to look at, i find it very difficult to use to navigate around for a few reasons:

1.  in order to use the mapnav, i first have to click on it to get it to be in focus (not intuitive).  then i try to grab the map and drag it, but the exact shadowing of the box doesn't seem to exactly track my movements.  once i move it at all, the shadow never seems to go back to the top left corner.  this is very frustrating.  therefore, once i use it to navigate, it nolonger reflects where i am. see here:
![before_after_map_nav](https://cloud.githubusercontent.com/assets/5124411/4958106/cfca06ea-66aa-11e4-90c1-d8db62b66931.png)

2.  i cannot move the list by small increments.  with a traditional scrollbar, i am able to move rows and columns of a grid by one at a time, but this is basically not possible with the map-nav.  even if i could use the mouse scroller or two-fingered scroller on a trackpad or click-and-drag, it would be something.  here's a useful blog on this issue:  http://www.billdwhite.com/wordpress/2014/05/17/d3-scalability-virtual-scrolling-for-large-visualizations/  .  there's also a solution for a click-and-drag (though it isn't perfect):   http://codepen.io/ghiden/pen/EhBpy.  i think the users need this find-grained kind of navigation ability.  this scrollable table has a bar that disappears, and allows me to use arrowkeys too:  http://devforrest.com/examples/table/table.php

3.  i am unable to resize my viewport to see more rows and columns.  i have a very large screen, yet the phenogrid stays the same size no matter if i resize my browser window.  i would really like to be able to add as many rows or columns as i desire when i resize my screen.  if a dynamic resize based on browser window size isn't possible, then can you allow the user to configure their row/columns, or perhaps zoom in/out?  here's a nice one that has a much larger matrix of information (though it lacks scrollbars): http://bost.ocks.org/mike/miserables/...  this is still very legible even with the tiny font, can we do ours this size as a default?  here's something a bit different, it allows dragging to move around the screen, and a resize bar:  http://linkedjazz.org/network/.  this one has a nice drag selection to zoom in:  http://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/.  

please consider these needs when redesigning.

**Comment by VincentIII** [comment]
1 has been resolved in previous updates.  2 & 3 are still needed

**Comment by yuanzhou** [comment]
I think the point 1 and 2 have been addressed in the refactored phenogrid. And for 3, now you can config the number of columns/rows of the viewport. 

I do agree that we may need to display a different mini-map when there's only one or two or very few phenotypes. @harryhoch

**Comment by nlwashington** [comment]
as for 3, the user cannot configure how many cols they see.  this is taken care of only by the folks that have control of the grid installation.  maybe i want to see 1000 columns.  and maybe i want to see more than 30 at a time.  

ideally i would like to have a little doohickey that i can grab and drag to make the space larger for me to see, just like i can with this editor window in the bottom right corner.  there's even scrollbars in this window that i can use to click and drag.  i still don't understand why i can't have a scrollbar.  i believe @mellybelly and @cmungall might like scrollbars too.

**Comment by yuanzhou** [comment]
@nlwashington I'll talk to @harryhoch about the scrollbars. I think one of the biggest advantages of having a mini-map is to show a big picture of the distribution of those grid cells in terms of density. But it's hard to maintain a precise vertical/horizontal scroll solely with dragging the mini-map. Scrollbars fit this purpose better.

Back to 3, right now the sim search only returns 100 records in the json result, there's should be a way to specify the limit of the results. Or we can do incremental ajax calls. Or even predefine a dropdown menu with options to select how many columns/rows to show. We'll also need to think about the size of the canvas especially when Phenogrid is embedded within 3rd-party apps.

**Comment by harryhoch** [comment]
@nlwashington, we can certainly consider scrollbars. @yuanzhou, can you do a bit of digging to see how hard this is to do?

**Comment by yuanzhou** [comment]
@harryhoch @nlwashington I think I've added the scrollbars and make it interact with the minimap. 

Rules: 

- The appearance of mini map and scrollbars are based on the x and y counts. And the appearance of vertical scrollbar is decided by the y count, horizontal scrollbar is decided by x count. So if there are only two sources (phenotypes) but 10000 matched targets (say genes),  we only show the minimap and horizontal scrollbar. In this case the minimap is kinda similar to the scrollbar, but you can see the mini cells distribution. It's also my question if we still want to show the minimap in this case.

![capture](https://cloud.githubusercontent.com/assets/195873/11275853/97524990-8ead-11e5-9c65-e418ec4be505.PNG)


- Scrolling of the scrollbars will trigger the corresponding updates in the grid region as well as the shaded area movement in minimap.

- Movement of the minimap shaded area will trigger updates of the grid region as well as the scrollbars.

Some addition screenshots:

![capture](https://cloud.githubusercontent.com/assets/195873/11275884/acabcbcc-8ead-11e5-8dcf-19cc9b3cd018.PNG)

![capture](https://cloud.githubusercontent.com/assets/195873/11275909/c112af40-8ead-11e5-8ff1-4a607d47575f.PNG)

Additional questions:

1. Do we really want/need to add the left/right or top/down arrorws on each side of the scrollbar? I feel it may be a little harder to add those fine-grade controls.

2. I think this scrolling feature can be released as part of the Xmas  release. I'll need to more testing to cover some corner cases. Any thoughts?

**Comment by yuanzhou** [comment]
@harryhoch Made some styling tweaks based on your suggestion:

![capture22](https://cloud.githubusercontent.com/assets/195873/11305476/d5c7490a-8f7a-11e5-8501-d35bccdb5a15.PNG)

and I also applied a different color while dragging the slider:

![capture](https://cloud.githubusercontent.com/assets/195873/11305498/f7425ad4-8f7a-11e5-927e-dc0a0a2aa41a.PNG)

**Comment by harryhoch** [comment]
@yuanzhou - nice! Thanks!

**Comment by yuanzhou** [comment]
Merged via PR #220
