### ISSUE TITLE
Design considerations about adjusted columns/rows after inverting axis

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#221]
This issue is related to #137 but needs some different discussions.

When we dynamically adjust the number of columns/rows based on the containing div's width/height, we could use more display space to show more grids. It comes to the question when we need to invert the axis. Say we are displaying 60 visible columns (100 total) and only 30 visible rows (100 total) within the current containing div. When inverting, the containing div's width and height won't change, so the best way is to still display 60 columns and 30 rows. But when we only have 30 total rows and 100 columns, after inverting, we'll just show 30 rows and 30 columns. It should be very common that we have more than 100 target columns and far less source phenotypes. If the containing div stays the same size, we'll end up only showing "the number of original rows" columns after inverting and may have a huge whitespace on the right for a wider screen.

This seems like a situation that we haven't captured in the current design, since in most cases, we show the same number of columns/rows, and inverting flips the whole grid without taking into the consideration that the containing div stays the same. Especially when we run phenogrid inside monarch, there's nothing below the grid, so the containing div's height changes accordingly. But in a more realistic world, phenogrid can be embedded into any section of the webpages within a fixed size of containing div. We won't be able to adjust the height of containing div after inverting. 

@harryhoch @nlwashington any insights?

**Comment by harryhoch** [comment]
@yuanzhou, I think this is a relatively minor point. We might provide some guidance for potential users,  for example, by indicating that inverted displays might want to be careful about the size of the containing div. If they size things right, there should not be a problem. That might be the best we can do....

**Comment by yuanzhou** [comment]
@harryhoch got it. Does this also mean that I don't have to worry about the inverting and just keep what we have now?

**Comment by yuanzhou** [comment]
This issue is relatively minor in the current development goals after discussion. So I'll close it. Will re-open it if it's needs to be addressed in the future.
