### ISSUE TITLE
One off error in species separator for mouse-zebrafish

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/phenogrid#222]
The species separator between mouse and zebrafish genes appears 1 field to the right of the first zebrafish gene.  See http://monarchinitiative.org/disease/OMIA:001158-9796 as an example.

**Comment by yuanzhou** [comment]
Thanks @kshefchek, I've fixed this error and merged the PR. Also updated the npm version. When you have a chance, please also push this to the production server.
