### ISSUE TITLE
Don't display Unmatched Phenotypes if there are no unmatched phenotypes

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/phenogrid#228]
This is just confusing clutter if it's not being used e.g.

http://monarchinitiative.org/genotype/MONARCH:8560659805ad3d04985228f2bc2d7b92

Related to: #173

**Comment by yuanzhou** [comment]
Thanks @julesjacobsen, I'll add a check and hide this Unmatched Phenotypes when this's no unmatched.
