### ISSUE TITLE
configuration of index page

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#232]
index page currently is hard coded to go straight to beta. We should revise to  have index page configuration be dynamically inferred from web pgae url, so that production page will hit the production server.

**Comment by yuanzhou** [comment]
How can you dynamically infer the serverURL from web page? If any third parties use Phenogrid, the default serverURL should be the monarch production. Should I change all the beta to production in index page? And only use beta for testing purposes?

**Comment by harryhoch** [comment]
in Javascript window.location.hostname should give the URL.  jQuery might have some cleaner way of doing it. 

otherwise, defaulting to production for third-party and the index page  sounds right

**Comment by yuanzhou** [comment]
Since we've agreed to have a simplified index.html pointing to the production server and I've committed the changes. I'm closing this issue.
