### ISSUE TITLE
indication of IC of terms (source, target, & match)

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/phenogrid#24]
we currently indicate via shading the similarity between the terms (source/target) in common between the query and targets.  

however, we should think about additionally indicating the IC of the source terms...this will give the user an indication of how rare that given phenotype is in the entirety of phenotypic data in the system.  some options to indicate the value for each (row) would be:
1.  list the numeric value, just as we list the match score for each column (and allow sorting on this option)
2.  row-header shading based on the value
3.  font size or row-height sizing based on value (this might be visually weird)

**Comment by yuanzhou** [comment]
Actually Mike has added the frequency of each phenotype in the phenotype tooltip. And by default, all the phenotypes are sorted by frequency. I'll think about other options.

**Comment by harryhoch** [comment]
ok, so close this
