### ISSUE TITLE
fix explanatory text for similarity scores

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#246]
I think the explanatory text associated with the similarity calculations might be a bit wrong. 

For uniqueness, we say
 This is simply a reflection of the IC normalized based on the maxIC. 
IC(PhenotypeInCommon)maxIC(AllPhenotypes)

I think there should be a division between those factors, not a mulitplication, so it should read...

IC(PhenotypeInCommon)/maxIC(AllPhenotypes)

Similarly, for ratio, we have
Ratio(q) is the proportion of shared information between a query phenotype and the phenotype-in-common with the target. ratio(q)=IC(lcs)IC(q)*100
**Ratio(t)<\/b> is the proportion of shared information between the target phenotype and the phenotype-in-common with the query. ratio(t)=IC(lcs)IC(t)*100

Again, it seems that terms should be divided to give us ratio(q)=IC(lcs)/IC(q) * 100 and similar for ratio (t).

@cmungall , are my interpretations correct? thanks.

**Comment by yuanzhou** [comment]
@harryhoch I'll get this fixed once @cmungall confirms this. Thanks!

**Comment by cmungall** [comment]
+1
