### ISSUE TITLE
misalignment of unmatched phenotypes link

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/phenogrid#247]
displaying in-line with the matched phenotypes

<img width="1440" alt="misaligned" src="https://cloud.githubusercontent.com/assets/796636/15808216/cfb4c810-2b26-11e6-9cf7-8a79382d9ea0.png">

**Comment by harryhoch** [comment]
@yuanzhou , this looks like an edge case. please take a look.

**Comment by yuanzhou** [comment]
I'm working on fixing it.

**Comment by yuanzhou** [comment]
@mellybelly thanks for reporting this issue. The misalignment was caused as a result of those "No matches" message on the top. The Unmatched link was aligned based on the phenogrid container but failed to take the height of those messages into account. I fixed this by moving those message to outside of the container.
