### ISSUE TITLE
Add options menu to top left

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#249]
With the increase in the number of species in phenogrid, it is now usually impossible to see the options menu until well below the fold. I recommend moving the menu to the top left where it will be more readily seen. This recommendation is for both analyze phenotypes and for the compare tab. Thoughts? This could also be a quick fix for the c elegans duplication issue. https://github.com/monarch-initiative/monarch-app/issues/1304

 
<img width="931" alt="screen shot 2016-07-11 at 5 19 59 pm" src="https://cloud.githubusercontent.com/assets/3658863/16751108/cd9404b6-478b-11e6-8ee8-c98df0939690.png">
----------------------------------THE FOLD LIES HERE ----------------------------------
     <img width="979" alt="screen shot 2016-07-11 at 5 20 10 pm" src="https://cloud.githubusercontent.com/assets/3658863/16751110/cf5ad888-478b-11e6-8bbf-ead0fd6a0fb3.png">

Related to https://github.com/monarch-initiative/phenogrid/issues/224

**Comment by harryhoch** [comment]
@jmcmurry, no argument there, but that's not because of the number of species - that's the number of phenotypes..

**Comment by jmcmurry** [comment]
you're right; however, the further from the left the menu gets, the less obvious it is, I think.

**Comment by jmcmurry** [comment]
A side benefit of this is that when unselecting taxon boxes, the options menu doesn't bounce all over the place as it does below.

<img width="1334" alt="screen shot 2016-07-11 at 9 02 22 pm" src="https://cloud.githubusercontent.com/assets/3658863/16754803/484d61c4-47ab-11e6-9351-2711677324f9.png">
<img width="1333" alt="screen shot 2016-07-11 at 9 02 14 pm" src="https://cloud.githubusercontent.com/assets/3658863/16754805/484eda22-47ab-11e6-95d7-526a747bddbf.png">
<img width="1334" alt="screen shot 2016-07-11 at 9 02 01 pm" src="https://cloud.githubusercontent.com/assets/3658863/16754804/484db9a8-47ab-11e6-896b-5e9aa67907ed.png">
