### ISSUE TITLE
Replace the species "compare" in phenogrid 

### ISSUE THREAD

**Issue by cborromeo** [monarch-initiative/phenogrid#253]
The phenogrid displays the text "Species: compare" in the hoverbox for a column when the user accesses phenogrid through the Analyze interface (see below).  The text should correspond to its actual species represented by the gene in the column.
<img width="462" alt="column_hover" src="https://cloud.githubusercontent.com/assets/5503816/17034938/d10aec30-4f52-11e6-8ef7-d37e35bf4f05.png">

**Comment by cborromeo** [comment]
@jmcmurry @harryhoch My changes are deployed to beta.monarchinitiative.org (which looks like it is down as of 10:26 AM EST July 25 Jeremy said he took beta down).  I tested my changes and I noticed a problem with the data returned by /compare.  The /compare code (used by the Analyze page) and the /simsearch/phenotype (used by the Disease page) handle the taxa differently.  The /simsearch/phenotype properly handles the taxon by assigning each column a species.  The compare code only assigns a taxon if the column is a human gene (see screenshot). 

At this point my code behaves correctly, but the data returned by /compare is incomplete.  Should I add an issue on the monarch-app issue tracker requesting the /compare code to add the taxon information for non-humans?   


![screen shot 2016-07-25 at 10 20 42 am](https://cloud.githubusercontent.com/assets/5503816/17104889/e118240a-5252-11e6-9ff1-ad1aa1f7eef4.png)

**Comment by harryhoch** [comment]
so in #4 above it does not have the taxon for 19090, where it should, as it does for #5? looks like a bug to me...

**Comment by cborromeo** [comment]
@harryhoch That's correct.  I deliberately mixed human and non-human genes into the Analyze "Gene IDs" text box.  The only ones returning taxon data are the human genes.

**Comment by cborromeo** [comment]
@harryhoch @yuanzhou this appears to have been reported by Zhou: https://github.com/monarch-initiative/monarch-app/issues/1024.  I followed the thread, but I don't see a resolution.

**Comment by yuanzhou** [comment]
@cborromeo @harryhoch as far as I can remember, the issue #1024 was not fully addressed. It was addressed for a short time of period then I encountered that "Not specified" again later. And I also remembered that I had the same issue several months ago. It should a data issue since the taxon needs to be returned from owlsim.

**Comment by kshefchek** [comment]
This will be fixed with https://github.com/monarch-initiative/monarch-app/pull/1315

**Comment by harryhoch** [comment]
I think this is fixed
