### ISSUE TITLE
Remove conversion of curies to fragments

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/phenogrid#259]
Right now phenogrid converts curie formatted IDs to fragments here:
https://github.com/monarch-initiative/phenogrid/blob/master/js/dataloader.js#L869

However, this is from an outdated requirement and results in manipulating the ID in other areas:
https://github.com/monarch-initiative/phenogrid/blob/master/js/dataloader.js#L785
https://github.com/monarch-initiative/phenogrid/blob/master/js/dataloader.js#L765
etc.

On the monarch app side we forward the URLs to the curie formatted ID.  It would clean up the code quite a bit if we get rid of this.

I'm happy to make a PR unless someone else feels inclined.  Would this affect any upstream users of phenogrid?

**Comment by yuanzhou** [comment]
@kshefchek I'm not sure if this will affect the integrated Phenogrid on the IMPC site. @harryhoch may have a better idea. But if you create a PR, I'm happy to merge it to the master then bump the npm version.
