### ISSUE TITLE
Matched term is from MP within the homo sapiens section of the phenogrid

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#263]
![image](https://user-images.githubusercontent.com/3658863/47464208-62aad400-d79d-11e8-8a1a-75d281208c3d.png)

**Comment by kshefchek** [comment]
Dupe of #264 (I think?) @jmcmurry pls reopen if I'm mistaken.

**Comment by jmcmurry** [comment]
yes; a dupe; there was a glitch and I didn't realize that it posted
