### ISSUE TITLE
don't display species in selector if no data

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/phenogrid#33]
If there is no data for a given species, then it should not be shown in the species selector. For example, here: http://tartini.crbs.ucsd.edu/disease/OMIM:610297
 if you click drosophila, you end up with a blank phenogrid page (as per #28 )

**Comment by yuanzhou** [comment]
Make the no-data-species checkbox disabled even if it's set as `active: true` in config file. This needs to check the compare species array.

**Comment by yuanzhou** [comment]
Fixed and merged in PR #175
