### ISSUE TITLE
spinner 

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#43]
the spinner markup doesn't seem to be visible - try loading /disease/OMIM:255800 and switch organism from overview to human. Instead of seeing the spinner/progress bar, the screen goes blank.

**Comment by VincentIII** [comment]
I'm having difficulty recreating this bug.  I tried that disease as well as a few others and this is the results I get:

Chrome: No Spinner, but sometimes takes 5-10 seconds to load between species. Data always loads
Firefox: Spinner shows up, but no animation and data loads shortly after.  Same amount of time on average as Chrome takes

**Comment by harryhoch** [comment]
hmm. sounds like you've recreated it, but unpredictably. Can you look into a revised spinner? I'm trying to avoid a blank screen when  there is a data reload.

Most of the processing time is on the owlsim server side, so comparable speeds are to be expected.

-harry

**Comment by harryhoch** [comment]
could not duplicate

**Comment by yuanzhou** [comment]
Removed from most recent version.
