### ISSUE TITLE
info box css transparent background

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#47]
on UDPICS, the info box comes up with a transparent background. Please check:

![updics-phenogrid-infopopup](https://cloud.githubusercontent.com/assets/174707/6045520/af341ce6-ac68-11e4-9fe2-4e77d77cf0a5.png)

**Comment by VincentIII** [comment]
New class added that encompasses all of the background for the object now.  Works on my environment and should be a unique enough name that it shouldn't be overwritten by any of their CSS.
