### ISSUE TITLE
issue with display of phenogrid in UDPICS

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/phenogrid#48]
this error was reported by the UDPICS folks.

>One of our engineers from RuRo sent us a screenshot (attached) to confirm
it’s an issue on the Monarch side — perhaps this helps in some way?

![screen shot 2015-02-12 at 3 52 36 pm](https://cloud.githubusercontent.com/assets/5124411/6177988/cbd99d3c-b2bf-11e4-98cf-ee1635c4cc89.png)

**Comment by VincentIII** [comment]
This is most likely from not having JSHashtable library installed on their setup.  They can get it from here:

http://www.timdown.co.uk/jshashtable/index.html
