### ISSUE TITLE
Add options for custom endpoints

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/phenogrid#49]
It would be nice to be able to define custom server endpoints. For the moment I'm forced to define a route like:

```
/simsearch/phenotype?input_items=...
```

**Comment by nlwashington** [comment]
i think this is necessary for #17, and for displaying user-entered comparisons (as opposed to search) https://github.com/monarch-initiative/monarch-app/issues/522 and https://github.com/monarch-initiative/monarch-app/issues/325.

**Comment by harryhoch** [comment]
Not sure what is meant here - please provide more detail.

**Comment by jnguyenx** [comment]
By default the Phenogrid will call a default path, the one mentioned above. It lacks of flexibility when one tries to connect another source of information, for instance what if I need more flags, etc..?

Another solution would be to let Phenogrid consume directly a JSON, so it become agnostic of the source of information, it can be a webserver, a file, etc...

**Comment by harryhoch** [comment]
ok, thanks. This relates to both https://github.com/monarch-initiative/monarch-app/issues/555 and https://github.com/monarch-initiative/phenogrid/issues/52.

**Comment by yuanzhou** [comment]
Can we close this @harryhoch ? Phenogrid still uses that `/simsearch/phenotype?input_items=` to get the simsearch result. And it uses `compare/` api for comparing a list of phenotypes with a list of genes.

**Comment by harryhoch** [comment]
Please leave this open, as per @nlwashington's comments above.

**Comment by yuanzhou** [comment]
@harryhoch I'm a little confused. I checked out Nicole's comments and what she mentioned have already been taken care of. And basically she said we should keep this hard coded route config. Did I miss anything?

**Comment by harryhoch** [comment]
@yuanzhou, ok, thanks. If this is done, then close it. More likely that I missed something.
