### ISSUE TITLE
Handle long labels

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/phenogrid#50]
I would suggest to leave the cropped version of the label and add a popover with the full label on a hover.

![pheno1](https://cloud.githubusercontent.com/assets/4312088/6419578/36c4fc9a-be73-11e4-935e-151a1782ea5e.png)
![pheno2](https://cloud.githubusercontent.com/assets/4312088/6419579/36d61e30-be73-11e4-8eb1-3efe65e6b1f1.png)

**Comment by VincentIII** [comment]
Fixed with https://github.com/monarch-initiative/phenogrid/commit/f8d2f3c2985c2f855ab6d144112f356c2e0abc88
