### ISSUE TITLE
phenogrid-format validator

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/phenogrid#52]
in order for other systems to use phenogrid, we need to provide a validator.  this could be a service and/or a standalone tool/script.  i think this is really important so that other groups who want to show their comparative data in our grid can, in particular with response to any changes in the way that phenogrid handles the incoming data structure.  i, for one, don't know what data in the given owlsim output is required for the grid.

**Comment by harryhoch** [comment]
Assume you mean a "validate that data as provided is appropriate for phenogrid" validator?

**Comment by nlwashington** [comment]
yes, a simple tool that parses the data that phenogrid renders, and reports if it fails to:
1.  parse
2.  has required data elements for rendering

**Comment by harryhoch** [comment]
@davism84 @yuanzhou please close this issue if you add the format validator to test cases.

**Comment by yuanzhou** [comment]
Added API JSON validation in mocha tests.
