### ISSUE TITLE
Location of Right Rect Overlaps based on models displayed, not axis length

### ISSUE THREAD

**Issue by VincentIII** [monarch-initiative/phenogrid#54]
If for some reason the modelData that is loaded does not fill out the full x-axis length, the Right Rect will start overlapping with the Center Rect.  It seems everything is being positioned off of what ends up being displayed from modelData, not from the length of Center Rect's content.  This should be fixed to avoid issues like below:

![screenshot from 2015-03-20 12 12 32](https://cloud.githubusercontent.com/assets/800672/6755583/a0d8609e-cefa-11e4-8d95-4fe4855e8cc9.png)

**Comment by VincentIII** [comment]
So this bug only appears as a companion bug when other issues may come up.  If you have less than 30 items on the X-Axis at load, it will look correctly.  However if for some reason you load at 30+ and fall below 30 at any point, it will cause this issue.  Its likely because the functions _createGridlines and _highlightSpecies (What creates the borders) are both built based off of what the X & Y max limits are.  

While _createRectangularContainers is also based off limits and should fix this issue _createModelRect (what actually displays the matches) will only display what it can, so any point there is missing values like above, it will cause the bug to appear.

**Comment by davism84** [comment]
with the refactored version this issue would be resolved
