### ISSUE TITLE
Labels for gradient not visible for non-homo-sapiens species

### ISSUE THREAD

**Issue by VincentIII** [monarch-initiative/phenogrid#55]
![screenshot from 2015-03-26 11 09 47](https://cloud.githubusercontent.com/assets/800672/6849288/c7dc146c-d3a8-11e4-8d09-cd951f5ceaad.png)

For some reason when you are looking at any species on its own other than homo-sapiens it will not display the gradient label next to the gradient.  There is a bug in the _createGradients function where the variable Y is increased by a factor of 180 (so 360 for the third species) which pushes the display of the label off the page

**Comment by yuanzhou** [comment]
I've notice this too yesterday. Will look into it.

**Comment by yuanzhou** [comment]
It's a weird javascript issue. 

````javascript
y = y1 + gradientHeight * i + gradientHeight + self.state.yoffset - 1;
````

generates the correct result but 
````javascript
y = y1 + gradientHeight * (i + 1) + self.state.yoffset - 1;
````
won't produce the same.

The bug was caused by using the second expression, after some debugging, I realized only using the first expression will fix this issue. Will do more research on this JS thing.

**Comment by yuanzhou** [comment]
It turned out that that `i` is a string.

**Comment by yuanzhou** [comment]
Did more debugging around this issue, turned out that the `i` was returned from `_getTargetSpeciesIndexByName()` which returns the index, and index is a string.

![t](https://cloud.githubusercontent.com/assets/195873/8942970/434d5350-3546-11e5-882b-f170e284a88a.png)

Used `parseInt()` to type cast into int.
