### ISSUE TITLE
fix external .js files accessible from a common location 

### ISSUE THREAD

**Issue by cborromeo** [monarch-initiative/phenogrid#57]
ask Harry about the stickyTooltip in js hashtable

can we use of npm package manager?  or phenogrid_config.js? for any external js files instead of adding them to pup_tent

**Comment by harryhoch** [comment]
relates to https://github.com/monarch-initiative/monarch-app/issues/597

**Comment by yuanzhou** [comment]
Should we close this issue? @harryhoch
