### ISSUE TITLE
Darkening of modelScoresLabel + xLines when mini-map moved

### ISSUE THREAD

**Issue by VincentIII** [monarch-initiative/phenogrid#58]
I just moved the modelScoresLabel into a more appropriate area and it made me notice a bug that likely has been around for a while but just now noticed.  On default this is what the line and mini-map look like:

![screenshot from 2015-04-09 13 40 46](https://cloud.githubusercontent.com/assets/800672/7072990/5774dbc0-debe-11e4-978e-cf33f08d8113.png)

However once you move the mini-map, it will darken them like the following:

![screenshot from 2015-04-09 13 40 57](https://cloud.githubusercontent.com/assets/800672/7072997/63bec288-debe-11e4-9cc2-e94a1e8e9a1d.png)

A likely solution would be to split the _createXRegion (and eventually the _createYRegion) into two functions.  The first one would be called when you do a minor change to the grid, such as changing the display colors, sort or moving the mini-map.  The other one would be called at initialization or each time data is fully reloaded into the hashtables.  The bug only shows up however when you move the map, and clears when you do any other changes, including changing of sort and display coloring.

**Comment by harryhoch** [comment]
thanks
> On 9 Apr 2015, at 1:45 PM, Vincent Agresti <notifications@github.com> wrote:
> 
> I just moved the modelScoresLabel into a more appropriate area and it made me notice a bug that likely has been around for a while but just now noticed. On default this is what the line and mini-map look like:
> 
> 
> 
> However once you move the mini-map, it will darken them like the following:
> 
> 
> 
> A likely solution would be to split the _createXRegion (and eventually the _createYRegion) into two functions. The first one would be called when you do a minor change to the grid, such as changing the display colors, sort or moving the mini-map. The other one would be called at initialization or each time data is fully reloaded into the hashtables. The bug only shows up however when you move the map, and clears when you do any other changes, including changing of sort and display coloring.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by nlwashington** [comment]
consider this ticket for general changes to the underlying code, not necessarily in response to mini-map specifically (as i think the mini-map should be deprecated #22)

**Comment by yuanzhou** [comment]
I noticed this issue too. Will look into it.
