### ISSUE TITLE
other cleanup

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#64]
move toward mvc

**Comment by harryhoch** [comment]
remove mentions of gene/phenotype, etc.

**Comment by yuanzhou** [comment]
Should this issue be closed?

**Comment by harryhoch** [comment]
not yet. we still have too many places in the code where "species" "phenotype", etc. are being used.

**Comment by harryhoch** [comment]
@davism84, please close this when appropriate.

**Comment by davism84** [comment]
not quite MVC, but all UI and data management are generally separated, with accessors methods and minimal coupling.  all data structures have been generalized to three basic structures target, source and cell data
