### ISSUE TITLE
localize mention of specific types to subfiles/objects

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#65]

**Comment by yuanzhou** [comment]
Can you provide more info about this? @harryhoch

**Comment by harryhoch** [comment]
terms like "species", "gene", "phenotype", etc. should only be used in configurations /options, and in a way that is abstracted and generalized as much as possible.

**Comment by davism84** [comment]
all variables generalized to target, source and targetGroup.

[see wiki] (https://github.com/monarch-initiative/phenogrid/wiki/Key-structures)

**Comment by yuanzhou** [comment]
I've also updated according behave tests based on the text change.
