### ISSUE TITLE
hover over has a mislabeled entry

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/phenogrid#66]
It should say disease or genotype or model but instead it says phenotype

![phenogriderror](https://cloud.githubusercontent.com/assets/796636/7335366/339dab08-eb6d-11e4-9124-6d9ac61732a1.png)

for humans, I think this should be disease. For a model organism, I think model is probably best, as in some cases it won't be a genotype.

**Comment by harryhoch** [comment]
@davism84 or @cborromeo , please take a look

**Comment by yuanzhou** [comment]
I'm fixing this bug. So
human: disease
mouse: gene
fish: gene

When should I use model or genotype? @harryhoch

**Comment by harryhoch** [comment]
When we drill down into the constituent genotypes for mouse/fish, we will be comparing to genotypes..

> On 29 Jul 2015, at 9:47 AM, yuanzhou <notifications@github.com> wrote:
> 
> I'm fixing this bug. So
> human: disease
> mouse: gene
> fish: gene
> 
> When should I use model or genotype? @harryhoch
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by yuanzhou** [comment]
For the current master branch, there's no genotype, only disease or gene, am I correct? @harryhoch

**Comment by harryhoch** [comment]
yes
> On 29 Jul 2015, at 9:56 AM, yuanzhou <notifications@github.com> wrote:
> 
> For the current master branch, there's no genotype, only disease or gene, am I correct? @harryhoch
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by yuanzhou** [comment]
Caused by the use of jquery's extend() without considering the x and y flip. extend({}, obj1, obj2), if obj1 and obj2 have the same properties, the ones in obj2 will overwrite the ones in obj1.
