### ISSUE TITLE
Split phenogrid.css into file for widget and file for index.html

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/phenogrid#67]
I found when embedding the widget into a ZFIN page that phenogrid.css affects html at the body level, rather than just in the widget.  

Secondarily, it might also be a good idea to use more specific css rules or class names, since sites may already have elements with ids like "logo" or "header", or maybe even the class name "tip"

**Comment by harryhoch** [comment]
@kevinschaper, I  think I have fixed this with https://github.com/monarch-initiative/phenogrid/commit/3b435696a74e5006dccf917c3ac1fa27f2bafb40. Please give it a try.

**Comment by harryhoch** [comment]
@midavis, this fix has many small changes in css and js. Might be a bit of a pain to merge with some of your code, but shouldn't really overlap. Mirrored in monarch-app as usual
