### ISSUE TITLE
expando-icons don't work

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#68]
@davism84 , the hpo expand icons don't work when one is loading phenogrid outside of monarch-app. I think this may be a path problem . please investigate.

**Comment by yuanzhou** [comment]
It's due to the image relative path. I've gotten it resolved in the phenogrid widget, will test it out or find a way to specify the absolute path for use in monarch-app.

**Comment by yuanzhou** [comment]
Already fixed. Will close this issue once I push the code changes to master branch.
