### ISSUE TITLE
convert info icons to fontawesome

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/phenogrid#72]
to reduce dependencies and issues with images, consider using [fontawesome](http://fortawesome.github.io/Font-Awesome/cheatsheet/) for the info buttons

**Comment by nlwashington** [comment]
consider fa-info-circle ```[&#xf05a;]```

**Comment by yuanzhou** [comment]
Another option is to use CSS sprite--a collection of images put into a single image. I'll check out fontawesome to see if there's any cross-browser problems. And work on this.

**Comment by yuanzhou** [comment]
@nlwashington I've replaced the green info icon with fontawesome icon. It's great that we don't have to link to the image path. Will continue working on the rest. If you want to see the code, please go to the zy branch. 

![capture](https://cloud.githubusercontent.com/assets/195873/8464257/d91bb3f6-200e-11e5-8c74-557bb4f7c7c6.PNG)

**Comment by yuanzhou** [comment]
All images are replaced with font awesome icons. Except the monarch logo.
