### ISSUE TITLE
convert monarch logo to svg

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/phenogrid#73]
a suggestion is to convert the monarch logo into an svg, so that all things on phenogrid are scalable.

**Comment by yuanzhou** [comment]
I had the same thought and mentioned to Harry last week, will work on this later.

**Comment by yuanzhou** [comment]
@nlwashington Do you have the PSD file or the original logo file? We may be able to export it to SVG in Fireworks or other tools.

**Comment by yuanzhou** [comment]
Got the AI file saved as SVG from Nicole. Looks great in browser. Will add this to phenogrid.
