### ISSUE TITLE
add toggle to hide minimap

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/phenogrid#74]
when refactoring the minimap, please consider adding a toggle to hide the whole rightside column.  (as suggested by @mjshepherd and @phenotips)

**Comment by yuanzhou** [comment]
In the current refactoring version, the minimap has been placed to in the left corner. 

![capture](https://cloud.githubusercontent.com/assets/195873/9494649/235b8f12-4bd5-11e5-860e-8f6fed5e3cf5.PNG)
