### ISSUE TITLE
buggy highlight on every 2nd entry

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/phenogrid#75]
as noticed by @mjshepherd, the phenogrid (including the one on the monarch's /page/phenogrid) has odd behavior in that the col/row highlights only occur on every 2nd entry to a given cell.  you can repeat this by mousing into a cell (where the highlights occur), then gently mousing out, then remousing in and it won't highlight, then mouseout again, and remouse in.  the final time it will highlight.

**Comment by yuanzhou** [comment]
Fixed by removing unnecessary code.
