### ISSUE TITLE
List of HP ids for a DOID is too long for API

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/phenogrid#78]
We're fetching the collection of HP ids for a DOID, then feeding that to phenogrid.  For some terms, like DOID:2256, passing the list of HP ids to tartini.crbs.ucsd.edu fails with a "414 (Request-URI Too Large)" error.  

If the server will take a post, that would be a quick way to solve it.   Alternatively, on the server side, it might be handy to have an endpoint that would take a DOID, just to get it all done in one request.

Here's the url that we're generating for that disease term:

http://tartini.crbs.ucsd.edu/simsearch/phenotype?input_items=HP:0000768+HP:0000926+HP:0002650+HP:0002655+HP:0002857+HP:0002938+HP:0002942+HP:0002945+HP:0002970+HP:0003184+HP:0003301+HP:0003370+HP:0006429+HP:0000926+HP:0000945+HP:0001155+HP:0002812+HP:0002829+HP:0002857+HP:0003365+HP:0003411+HP:0004322+HP:0006398+HP:0002761+HP:0002938+HP:0002970+HP:0004322+HP:0002084+HP:0002695+HP:0007385+HP:0000316+HP:0002084+HP:0002695+HP:0002697+HP:0005280+HP:0007385+HP:0012811+HP:0000179+HP:0000248+HP:0000252+HP:0000280+HP:0000286+HP:0000294+HP:0000377+HP:0000445+HP:0000470+HP:0000639+HP:0000664+HP:0000926+HP:0000945+HP:0000951+HP:0001007+HP:0001249+HP:0001251+HP:0001252+HP:0001498+HP:0002162+HP:0002651+HP:0002868+HP:0003085+HP:0003180+HP:0003301+HP:0005121+HP:0100864+HP:0000270+HP:0004960+HP:0005304+HP:0005474+HP:0005855+HP:0000023+HP:0000260+HP:0000270+HP:0000311+HP:0000520+HP:0000883+HP:0000926+HP:0000938+HP:0001263+HP:0001388+HP:0001552+HP:0002645+HP:0002650+HP:0002808+HP:0002953+HP:0002980+HP:0002982+HP:0002986+HP:0003100+HP:0003783+HP:0003784+HP:0004331+HP:0005855+HP:0008873+HP:0010049+HP:0000164+HP:0000478+HP:0000926+HP:0000938+HP:0001939+HP:0002644+HP:0002645+HP:0002757+HP:0004322+HP:0004586+HP:0005084+HP:0006394+HP:0008422+HP:0030268+HP:0000248+HP:0000325+HP:0000592+HP:0000703+HP:0000938+HP:0000951+HP:0001388+HP:0002751+HP:0002953+HP:0003179+HP:0004322+HP:0004586+HP:0008422+HP:0000193+HP:0000218+HP:0000494+HP:0000592+HP:0000668+HP:0000684+HP:0000689+HP:0000926+HP:0000938+HP:0000963+HP:0000974+HP:0000978+HP:0001073+HP:0001182+HP:0001388+HP:0001763+HP:0002515+HP:0003016+HP:0003301+HP:0003370+HP:0003393+HP:0008848+HP:0009803+HP:0010049+HP:0100490+HP:0002651+HP:0000926+HP:0004322+HP:0000023+HP:0000272+HP:0000325+HP:0000341+HP:0000347+HP:0000348+HP:0000586+HP:0000592+HP:0000703+HP:0000774+HP:0000787+HP:0000883+HP:0000885+HP:0000926+HP:0000938+HP:0001290+HP:0001388+HP:0001620+HP:0002021+HP:0002650+HP:0002761+HP:0002857+HP:0002983+HP:0004322+HP:0004482+HP:0006528+HP:0011220+HP:0011800+HP:0000160+HP:0000218+HP:0000272+HP:0000324+HP:0000336+HP:0000347+HP:0000684+HP:0000768+HP:0000939+HP:0001270+HP:0002564+HP:0002645+HP:0002650+HP:0004322+HP:0005280+HP:0011220+HP:0011800+HP:0000233+HP:0000325+HP:0000337+HP:0000343+HP:0000411+HP:0000527+HP:0000592+HP:0000637+HP:0000768+HP:0000926+HP:0000939+HP:0001166+HP:0001252+HP:0001382+HP:0001537+HP:0002194+HP:0002645+HP:0002751+HP:0003202+HP:0004322+HP:0004325+HP:0011001+HP:0002857+HP:0000592+HP:0000883+HP:0000926+HP:0001263+HP:0002650+HP:0004322+HP:0012110+HP:0000470+HP:0000768+HP:0000926+HP:0001552+HP:0001763+HP:0003311+HP:0003521+HP:0004325+HP:0006009+HP:0006429+HP:0008812+HP:0010049+HP:0010743+HP:0000272+HP:0000405+HP:0001156+HP:0001270+HP:0001355+HP:0002512+HP:0002677+HP:0002761+HP:0002781+HP:0002938+HP:0003015+HP:0004060+HP:0005280+HP:0005733+HP:0008414+HP:0008905+HP:0011800+HP:0100864+HP:0100864+HP:0002665+HP:0003016+HP:0003021+HP:0003347+HP:0002979+HP:0003016+HP:0003025+HP:0000763+HP:0000926+HP:0001156+HP:0001377+HP:0001379+HP:0001380+HP:0001388+HP:0001498+HP:0002341+HP:0002515+HP:0002650+HP:0002663+HP:0002758+HP:0002808+HP:0002816+HP:0002829+HP:0002857+HP:0002938+HP:0002970+HP:0003016+HP:0003025+HP:0003026+HP:0003093+HP:0003311+HP:0003414+HP:0004236+HP:0004568+HP:0008873+HP:0009487+HP:0009882+HP:0010049+HP:0010236+HP:0010582+HP:0012307+HP:0100168+HP:0010582+HP:0010585+HP:0002990+HP:0003974+HP:0003982+HP:0004050+HP:0004231+HP:0005632+HP:0005736+HP:0005792+HP:0009802+HP:0009820+HP:0010048+HP:0010509+HP:0010744+HP:0010760+HP:0000926+HP:0003300+HP:0000581+HP:0001263+HP:0006429+HP:0100864+HP:0000767+HP:0000768+HP:0000773+HP:0000774+HP:0000887+HP:0001216+HP:0001821+HP:0002650+HP:0002812+HP:0002866+HP:0002869+HP:0002938+HP:0002970+HP:0002984+HP:0003022+HP:0003097+HP:0003099+HP:0003300+HP:0003498+HP:0004482+HP:0005736+HP:0005792+HP:0006438+HP:0008789+HP:0009638+HP:0009882+HP:0010017+HP:0010049+HP:0010241+HP:0010575+HP:0100864+HP:0001380+HP:0002659+HP:0002812+HP:0002953+HP:0003179+HP:0004568+HP:0004586+HP:0000189+HP:0000218+HP:0000894+HP:0002643+HP:0004220+HP:0009577+HP:0011800+HP:0000076+HP:0000235+HP:0000293+HP:0000316+HP:0000324+HP:0000336+HP:0000347+HP:0000347+HP:0000365+HP:0000520+HP:0000772+HP:0000774+HP:0000889+HP:0000944+HP:0001163+HP:0001166+HP:0001382+HP:0001671+HP:0002007+HP:0002093+HP:0002205+HP:0002650+HP:0002652+HP:0002982+HP:0003103+HP:0003272+HP:0003312+HP:0004322+HP:0004493+HP:0005446+HP:0009804+HP:0009882+HP:0010306+HP:0010511+HP:0011335+HP:0003301+HP:0001156+HP:0001387+HP:0002515+HP:0002656+HP:0002663+HP:0002761+HP:0002829+HP:0002857+HP:0002857+HP:0002970+HP:0002983+HP:0003272+HP:0003300+HP:0003301+HP:0003502+HP:0005743+HP:0006429+HP:0008800+HP:0008843+HP:0008873+HP:0009803+HP:0010049+HP:0010582+HP:0010585+HP:0100864+HP:0000160+HP:0000272+HP:0000311+HP:0000311+HP:0000405+HP:0000518+HP:0000518+HP:0000545+HP:0001156+HP:0001798+HP:0002673+HP:0002857+HP:0004322+HP:0005930+HP:0009803+HP:0012368+HP:0002654+HP:0002815+HP:0002829+HP:0003365+HP:0003370+HP:0006398+HP:0006407+HP:0030041+HP:0001156+HP:0002650+HP:0003422+HP:0004322+HP:0005107+HP:0005978+HP:0100589+HP:0001714+HP:0001718+HP:0001762+HP:0001763+HP:0002092+HP:0000175+HP:0000316+HP:0000336+HP:0002515+HP:0000365+HP:0000366+HP:0002194+HP:0001385+HP:0002650+HP:0002758+HP:0002808+HP:0003182+HP:0003370+HP:0004348+HP:0005041+HP:0005743+HP:0006429+HP:0008783+HP:0000494+HP:0001156+HP:0001376+HP:0001852+HP:0002687+HP:0003042+HP:0004493+HP:0005048+HP:0006487+HP:0008368+HP:0009601+HP:0009623+HP:0009642+HP:0009804+HP:0009882+HP:0009882+HP:0010041+HP:0010044+HP:0000218+HP:0000316+HP:0000337+HP:0000343+HP:0000365+HP:0000470+HP:0000535+HP:0000684+HP:0000687+HP:0000691+HP:0001156+HP:0001552+HP:0001629+HP:0001642+HP:0001650+HP:0001653+HP:0001659+HP:0002553+HP:0002655+HP:0002750+HP:0002751+HP:0002829+HP:0002857+HP:0002938+HP:0002945+HP:0002967+HP:0002982+HP:0003022+HP:0003031+HP:0010047+HP:0003042+HP:0003071+HP:0003090+HP:0003093+HP:0010055+HP:0003301+HP:0003417+HP:0003834+HP:0004976+HP:0005180+HP:0006067+HP:0006462+HP:0010109+HP:0006610+HP:0007598+HP:0008450+HP:0008551+HP:0008905+HP:0010109+HP:0009803+HP:0011001+HP:0010049+HP:0010446+HP:0010585+HP:0100490+HP:0100864+HP:0003026+HP:0000256+HP:0001156+HP:0001382+HP:0001831+HP:0002104+HP:0002644+HP:0002650+HP:0002652+HP:0002758+HP:0002823+HP:0002970+HP:0002983+HP:0003015+HP:0003307+HP:0003312+HP:0003416+HP:0004322+HP:0009811+HP:0100543+HP:0003521+HP:0004594+HP:0003090+HP:0002650+HP:0002655+HP:0002812+HP:0002866+HP:0008843+HP:0010582+HP:0000175+HP:0000272+HP:0000368+HP:0000773+HP:0000774+HP:0000883+HP:0000912+HP:0000926+HP:0000944+HP:0001156+HP:0001163+HP:0001561+HP:0001789+HP:0001831+HP:0002644+HP:0002970+HP:0002983+HP:0004322+HP:0005280+HP:0005716+HP:0005930+HP:0006703+HP:0009882+HP:0010306+HP:0002663+HP:0000121+HP:0000248+HP:0000316+HP:0000316+HP:0000347+HP:0000347+HP:0000347+HP:0000407+HP:0000452+HP:0000453+HP:0000520+HP:0000520+HP:0000692+HP:0000773+HP:0000774+HP:0000829+HP:0000829+HP:0000938+HP:0001156+HP:0002007+HP:0002150+HP:0002515+HP:0002737+HP:0002756+HP:0002983+HP:0003021+HP:0003026+HP:0003072+HP:0003072+HP:0003109+HP:0003155+HP:0003273+HP:0003510+HP:0004209+HP:0004209+HP:0004493+HP:0004676+HP:0005871+HP:0006380+HP:0006487+HP:0011001+HP:0100530+HP:0100759+HP:0000347+HP:0000365+HP:0000926+HP:0001156+HP:0001363+HP:0002007+HP:0002515+HP:0002812+HP:0002970+HP:0002970+HP:0002980+HP:0003072+HP:0003301+HP:0003371+HP:0003502+HP:0004348+HP:0005819+HP:0005871+HP:0006028+HP:0006208+HP:0006414+HP:0008833+HP:0009826+HP:0009844+HP:0009882+HP:0000162+HP:0000175+HP:0000272+HP:0000311+HP:0000347+HP:0000365+HP:0000488+HP:0000501+HP:0000518+HP:0000520+HP:0000541+HP:0000545+HP:0000926+HP:0001083+HP:0002697+HP:0001376+HP:0002093+HP:0002650+HP:0002652+HP:0002758+HP:0002777+HP:0002779+HP:0002808+HP:0002823+HP:0002983+HP:0003015+HP:0003272+HP:0003307+HP:0004322+HP:0004327+HP:0005280+HP:0010306+HP:0100625+HP:0200003+HP:0002676+HP:0002515+HP:0002656+HP:0002970+HP:0003071+HP:0003502+HP:0004279+HP:0005086+HP:0010582+HP:0000160+HP:0000325+HP:0000343+HP:0000347+HP:0000365+HP:0000444+HP:0000494+HP:0000506+HP:0000508+HP:0000534+HP:0000545+HP:0001156+HP:0001163+HP:0001196+HP:0001376+HP:0001537+HP:0001773+HP:0001831+HP:0002564+HP:0002652+HP:0002823+HP:0002857+HP:0002983+HP:0002992+HP:0003028+HP:0003063+HP:0004209+HP:0004322+HP:0005048+HP:0005105+HP:0008368+HP:0009465+HP:0010293+HP:0010669+HP:0010935+HP:0000008+HP:0000028+HP:0000046+HP:0000272+HP:0000316+HP:0000343+HP:0000347+HP:0001156+HP:0001163+HP:0002007+HP:0002999+HP:0003042+HP:0003196+HP:0005060+HP:0005280+HP:0005792+HP:0008736+HP:0009826+HP:0005623+HP:0005855+HP:0000365+HP:0000703+HP:0002659+HP:0002757+HP:0000362+HP:0000365+HP:0000592+HP:0000703+HP:0002645+HP:0002650+HP:0002757+HP:0002808+HP:0003023+HP:0003321+HP:0004322+HP:0005005+HP:0008905+HP:0002695+HP:0002697+HP:0001384+HP:0002656+HP:0002663+HP:0002758+HP:0003236+HP:0003502+HP:0003701+HP:0010049+HP:0010582+HP:0010585+HP:0000023+HP:0000256+HP:0000272+HP:0000343+HP:0000347+HP:0000463+HP:0000470+HP:0000474+HP:0000476+HP:0000772+HP:0000774+HP:0001156+HP:0001537+HP:0001561+HP:0001789+HP:0001789+HP:0001831+HP:0001883+HP:0002007+HP:0002564+HP:0002652+HP:0002983+HP:0003196+HP:0004322+HP:0004348+HP:0006703+HP:0010306+HP:0000774+HP:0002651+HP:0000926+HP:0000944+HP:0001156+HP:0001163+HP:0001288+HP:0001376+HP:0001382+HP:0001831+HP:0002650+HP:0002750+HP:0002758+HP:0002808+HP:0002829+HP:0002857+HP:0002970+HP:0002983+HP:0003049+HP:0003272+HP:0003307+HP:0003311+HP:0005930+HP:0011405+HP:0000175+HP:0000272+HP:0000316+HP:0000337+HP:0000365+HP:0000470+HP:0000501+HP:0000518+HP:0000541+HP:0000545+HP:0000639+HP:0000774+HP:0001883+HP:0002650+HP:0002652+HP:0002758+HP:0002808+HP:0002983+HP:0002996+HP:0003307+HP:0003312+HP:0004322+HP:0005930+HP:0008788+HP:0008800+HP:0010306+HP:0010501+HP:0002655+HP:0000175+HP:0000272+HP:0000316+HP:0000541+HP:0000545+HP:0000907+HP:0000926+HP:0001288+HP:0001883+HP:0002093+HP:0002650+HP:0002652+HP:0002758+HP:0002808+HP:0002823+HP:0002857+HP:0002970+HP:0002983+HP:0003025+HP:0003272+HP:0003307+HP:0003311+HP:0004322+HP:0005930+HP:0010306+HP:0011860+HP:0000175+HP:0000175+HP:0000316+HP:0000347+HP:0000582+HP:0002650+HP:0002812+HP:0002857+HP:0003042+HP:0003090+HP:0003370+HP:0004348+HP:0005105+HP:0006167+HP:0009826+HP:0010582+HP:0000077+HP:0000238+HP:0000256+HP:0000272+HP:0000274+HP:0000365+HP:0000520+HP:0000774+HP:0000889+HP:0000926+HP:0000944+HP:0000956+HP:0000973+HP:0001156+HP:0001171+HP:0001250+HP:0001250+HP:0001252+HP:0001252+HP:0001376+HP:0001561+HP:0001631+HP:0001643+HP:0002007+HP:0002093+HP:0002119+HP:0002187+HP:0002269+HP:0002652+HP:0002676+HP:0002808+HP:0002823+HP:0002823+HP:0002983+HP:0002991+HP:0002992+HP:0003026+HP:0004322+HP:0005280+HP:0006487+HP:0006487+HP:0006703+HP:0010306+HP:0010880+HP:0100543+HP:0100781+HP:0008909+HP:0002970+HP:0010591+HP:0010886+HP:0000926+HP:0001377+HP:0002515+HP:0002651+HP:0002750+HP:0002758+HP:0002997+HP:0002758+HP:0002812+HP:0002869+HP:0002970+HP:0002970+HP:0002980+HP:0002982+HP:0002986+HP:0003015+HP:0003021+HP:0003031+HP:0003071+HP:0004566+HP:0006603+HP:0008476+HP:0008905+HP:0010585+HP:0000944+HP:0002992&target_species=7955

**Comment by yuanzhou** [comment]
Switched from http get to http post for ajax request to simsearch. Resolved the 414 and 413 errors.

Also added check to remove duplicated phenotypes before sending the request to simsearch, speed improved too.
