### ISSUE TITLE
merge npm install stuff to master

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#79]
Seth has prototyped an npm-based configuration setup at https://github.com/monarch-initiative/phenogrid/tree/npm-config-kltm. 

We need to 
a) merge this to master
b) revise index.html appropriately
c) revise gh-pages appropriately.

**Comment by kltm** [comment]
I'm happy to field any questions about this. As well, once merged with master, I can help with the final steps of getting the documentation setup.

**Comment by harryhoch** [comment]
Thanks, @kltm. @yuanzhou is just joining the team. He'll likely look into this once he gets a chance to get oriented.

**Comment by yuanzhou** [comment]
I've started a new branch called zy, and merged the kltm into a copy of the master code. I'm making changes and fixing bugs in the zy branch now. Once it's in a good shape, I'll send a pull request so it can be merged into the master branch before the July release date.

**Comment by yuanzhou** [comment]
Have merged Dan's PR manually.
