### ISSUE TITLE
Labels of species overflow map rect

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#84]
![capture](https://cloud.githubusercontent.com/assets/195873/8438795/1ce76c80-1f36-11e5-8348-4378ea8f7e01.PNG)

**Comment by nlwashington** [comment]
Also, these probably will go away when we move to a single-color scheme (see #23)

**Comment by yuanzhou** [comment]
I've already fix this in the zy branch, will push more changes to master tomorrow. Yes, I like the idea of single color scale. I've also mentioned Harry about this idea. 

-----
I was doing readings on color selection in data visualization and found this site, http://colorbrewer2.com, mentioned in several articles. There are some good color scales based on research.

I'm thinking if it's a good idea of using one of their color schemes (consists of only 5 colors) and render all the similarity scores in 5 ranges (1-20, 21-40, 41-60, 61-80, 81-100), one color for each range. This way the similarity search can be reduced into a range instead of a specific number. It's lot easier to identify a color out of 5. Once the target range/color is locked, further search can be easier using the tooltip, which shows the actual score. 

Or we can use a color-outlined square for each cell, similar to the current design, but show the score right in the square. This makes the similarity easier to track/search together with the 5-color scheme.
