### ISSUE TITLE
Missing right and bottom borders of data cell tooltip

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#88]
![capture](https://cloud.githubusercontent.com/assets/195873/8546973/a16030de-2489-11e5-83db-81d2ac807017.PNG)

**Comment by harryhoch** [comment]
might be just an aliasing problem. Try a tooltip with either 2 pixel border or no border…

> On 7 Jul 2015, at 9:22 AM, yuanzhou <notifications@github.com> wrote:
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300
