### ISSUE TITLE
License needed for phenogrid code

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#90]
@harryhoch 
Recommendation is BSD-3 with Monarch Initiative as copyright holder [text here] (https://docs.google.com/document/d/1vC8zDPtmvyJy_UZ9m_LUVPpgsZkFz0AmLP14_ef21-I/edit)

**Comment by harryhoch** [comment]
@jmcmurry, will discuss in email. Hoping to get something up soon.

**Comment by yuanzhou** [comment]
@harryhoch do you have the license decided? If so, I can update that in the package.json before the release.

**Comment by harryhoch** [comment]
not yet, unfortunately.

**Comment by mellybelly** [comment]
@harryhoch will this be available before our release?

**Comment by harryhoch** [comment]
working on some feedback from our legal team.

**Comment by yuanzhou** [comment]
Phenogrid has been published on npmjs.org under GPL-2.0 license. @harryhoch can we close this issue?
