### ISSUE TITLE
Tooltips on hover over x-axis labels are a bit too sticky

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#91]
When I hover over x-axis labels on the grid and then move the mouse down the tooltip sticks until I mouse over another label. By contrast, the tooltip correctly disappears when mousing left, right or up from the label. Probably just a matter of tweaking the event listener.
![screen shot 2015-07-08 at 16 40 57](https://cloud.githubusercontent.com/assets/3658863/8584881/4592da10-2590-11e5-9e35-39bf5795d588.png)

**Comment by harryhoch** [comment]
@davism84, @yuanzhou, is this still a problem?

**Comment by yuanzhou** [comment]
@harryhoch still a problem now, Mike will be making changes to the tootip library later.

**Comment by davism84** [comment]
with updates/clean-up to stickytooltip I'm going to say this is resolved.  But continue to test this.
