### ISSUE TITLE
Organism should be documented when axis is in flipped mode

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/phenogrid#94]
Currently, what is now the "flipped" aka "inverted" mode lacks axis labels for organisms.

![screen shot 2015-07-14 at 23 17 14](https://cloud.githubusercontent.com/assets/3658863/8691996/89c5332a-2a7e-11e5-8101-a4c2b4475e91.png)

In pseudo-behave terms this would be:
````
I go to http://beta.monarchinitiative.org/disease/DOID:14330 
and I click on the "Compare" tab
the organism should always be visible.
````
Consider something like the below whereby the horizontal divider lines are extended into the axis, providing a natural frame for the axis group to be shown rotated 90 degrees:

![screen shot 2015-07-14 at 23 30 57](https://cloud.githubusercontent.com/assets/3658863/8692167/73338c54-2a80-11e5-81c4-1b4163410016.png)

**Comment by harryhoch** [comment]
@davism84, What do you think of this?

**Comment by yuanzhou** [comment]
Personally, I feel it's more eye-friendly if the labels for organisms to be placed on the right.

![capture](https://cloud.githubusercontent.com/assets/195873/8698897/809838be-2acf-11e5-815a-40a5fd99f297.PNG)

(I didn't have photoshop, so captured a screenshot of two overlapped images)

**Comment by harryhoch** [comment]
@yuanzhou , the problem is that we don't want to be dealing with layout mess on the right, which complicates matters.

@davism84, can we consider some sort of transient mouse-over that would show the target class (ie, organism) when we mouse over the right region?

**Comment by davism84** [comment]
inverted labels now appear on the left side

![image](https://cloud.githubusercontent.com/assets/10049022/9364895/9b379df4-467c-11e5-90bf-d7b75114aa42.png)
