### ISSUE TITLE
when phenotypes are on horizontal axis, use all the space

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/phenogrid#99]
For example, this page: http://beta.monarchinitiative.org/disease/OMIM%3A147920
if you flip the axis you still have to use the browser window to navigate to the right, even though all the phenotypes would fit on the page if the browser box wasn't there.

**Comment by harryhoch** [comment]
planned redesign will move the overview and color scales away from the right-hand side.

**Comment by yuanzhou** [comment]
Moved the overview map from the right.
